"""Add ON DELETE CASCADE to related tables

Revision ID: 4d618b353b77
Revises: 55c52eadf083
Create Date: 2025-06-10 11:41:41.939395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d618b353b77'
down_revision = '55c52eadf083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rgb', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rgb_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'main_datetime', ['datetime'], ['datetime'], ondelete='CASCADE')

    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sensor_data_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'main_datetime', ['datetime'], ['datetime'], ondelete='CASCADE')

    with op.batch_alter_table('wave_length', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('wave_length_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'main_datetime', ['datetime'], ['datetime'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_length', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wave_length_ibfk_1'), 'main_datetime', ['datetime'], ['datetime'])

    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sensor_data_ibfk_1'), 'main_datetime', ['datetime'], ['datetime'])

    with op.batch_alter_table('rgb', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rgb_ibfk_1'), 'main_datetime', ['datetime'], ['datetime'])

    # ### end Alembic commands ###
