"""Add ON DELETE CASCADE to related tables

Revision ID: 55c52eadf083
Revises: 
Create Date: 2025-06-10 11:39:06.975640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55c52eadf083'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.alter_column('nc',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('wave_length_white', schema=None) as batch_op:
        batch_op.alter_column('is_reference',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_length_white', schema=None) as batch_op:
        batch_op.alter_column('is_reference',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.alter_column('nc',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
